
server:
  port: 9003
  servlet:
    context-path: /api/v1/authentication-service

## MongoDB related properties
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: authentication-service
  data:
    mongodb:
      uri: mongodb://root:${mongodb-root-password}@${MONGODB_SERVICE_HOST}:${MONGODB_SERVICE_PORT}
      database: p2p
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

#Swagger
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

#Actuator
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show:
        details: always
    web:
      exposure:
        include:
          - prometheus
          - health
          - metrics
          - info
  security:
    enabled: false
endpoints:
  health:
    sensitive: false


secret: <secret>

errorMsgMap:
  ERR_DETAIL_NOT_FOUND: "Details could not be found. {0}"
  ERR_SAVING_DATA: "Error in saving data. {0}"
  ERR_UPDATING_DATA: "Error in updating data. {0}"
  ERR_DELETING_DATA: "Error in deleting data. {0}"
  ERR_JSON_TRANFORMATION_FAILURE: "Tranformation Fails. {0}"
  ERR_RESPONSE_NOT_FOUND: "No Response Received. {0}"
  ERR_RESPONSE_BODY_NOT_FOUND: "Details not found. {0}"
  ERR_AUTHENTICATION: "Unauthorized Access : {0}"